// diagramData.js - Exact Architecture Topology Specification matching the system design diagram

export const GROUP_BOXES = [
  // ─── Outer Cluster Boxes ───
  {
    id: 'box-external',
    label: 'EXTERNAL SERVICES',
    color: 'rgba(76, 175, 80, 0.04)',
    borderColor: 'rgba(76, 175, 80, 0.4)',
    borderDash: [6, 4],
    x1: -420,
    y1: -440,
    x2: 120,
    y2: -290,
  },
  {
    id: 'box-client',
    label: 'CLIENT',
    color: 'rgba(206, 147, 216, 0.04)',
    borderColor: 'rgba(206, 147, 216, 0.4)',
    borderDash: [6, 4],
    x1: -820,
    y1: -40,
    x2: -450,
    y2: 240,
  },
  {
    id: 'box-server',
    label: 'SERVER',
    color: 'rgba(66, 165, 245, 0.04)',
    borderColor: 'rgba(66, 165, 245, 0.4)',
    borderDash: [6, 4],
    x1: -430,
    y1: -230,
    x2: -90,
    y2: 260,
  },
  {
    id: 'box-mock-server',
    label: 'MOCK-SERVER (WORKER)',
    color: 'rgba(255, 213, 79, 0.04)',
    borderColor: 'rgba(255, 213, 79, 0.4)',
    borderDash: [6, 4],
    x1: 60,
    y1: -230,
    x2: 500,
    y2: 270,
  },
  {
    id: 'box-telemetry',
    label: 'TELEMETRY-SERVICE',
    color: 'rgba(137, 180, 250, 0.05)',
    borderColor: 'rgba(137, 180, 250, 0.45)',
    borderDash: [6, 4],
    x1: 540,
    y1: -40,
    x2: 900,
    y2: 240,
  },
  {
    id: 'box-gateway',
    label: 'GATEWAY & INGRESS LAYER',
    color: 'rgba(255, 167, 38, 0.04)',
    borderColor: 'rgba(255, 167, 38, 0.35)',
    borderDash: [6, 4],
    x1: -820,
    y1: 330,
    x2: 900,
    y2: 450,
  },

  // ─── Inner Sub-Boxes (Nested Containers) ───
  {
    id: 'sub-client',
    label: 'clients',
    color: 'rgba(206, 147, 216, 0.08)',
    borderColor: 'rgba(206, 147, 216, 0.3)',
    borderDash: [],
    x1: -640,
    y1: -15,
    x2: -470,
    y2: 215,
  },
  {
    id: 'sub-server',
    label: 'servers',
    color: 'rgba(102, 187, 106, 0.08)',
    borderColor: 'rgba(102, 187, 106, 0.3)',
    borderDash: [],
    x1: -285,
    y1: 25,
    x2: -115,
    y2: 240,
  },
  {
    id: 'sub-telemetry-app',
    label: 'app',
    color: 'rgba(137, 180, 250, 0.08)',
    borderColor: 'rgba(137, 180, 250, 0.3)',
    borderDash: [],
    x1: 560,
    y1: -15,
    x2: 720,
    y2: 215,
  },
];

export const NODE_DEFS = {
  // ─── External Domains (Very Bottom) ───
  'client.mockapi.info': {
    label: '🌐 client.mockapi.info',
    color: '#ce93d8',
    x: -660,
    y: 540,
    group: 'domain',
    description: 'Frontend Web Client Ingress Endpoint',
  },
  'server.mockapi.info': {
    label: '🌐 server.mockapi.info',
    color: '#42a5f5',
    x: -280,
    y: 540,
    group: 'domain',
    description: 'Core REST API Ingress Endpoint',
  },
  'curl-api.mockapi.info': {
    label: '🌐 curl-api.mockapi.info',
    color: '#ec407a',
    x: 40,
    y: 540,
    group: 'domain',
    description: 'Dynamic Mock API cURL Endpoint',
  },
  'opentelemetry.client.mockapi.info': {
    label: '🌐 opentelemetry.client.mockapi.info',
    color: '#89b4fa',
    x: 420,
    y: 540,
    group: 'domain',
    description: 'Telemetry UI Dashboard Endpoint',
  },
  'opntelemtry.server.mockapi.info': {
    label: '🌐 opntelemtry.server.mockapi.info',
    color: '#89b4fa',
    x: 760,
    y: 540,
    group: 'domain',
    description: 'Telemetry Ingestion API Endpoint',
  },

  // ─── Gateway Layer ───
  'Domain-service/CDN/Nginx': {
    label: '🌍 Domain-service / CDN / Nginx',
    color: '#ffa726',
    x: 40,
    y: 390,
    widthConstraint: { minimum: 780 },
    group: 'gateway',
    description: 'Edge CDN, SSL Termination, & Ingress Reverse Proxy',
  },

  // ─── Client Cluster ───
  'nginx-client': {
    label: '🌐 nginx-client',
    color: '#ce93d8',
    x: -740,
    y: 100,
    group: 'client',
    description: 'Client Load Balancer and SPA Reverse Proxy',
  },
  'client-1': {
    label: '💻 client-1',
    color: '#ba68c8',
    x: -555,
    y: 40,
    group: 'client',
    description: 'Frontend React Client Instance 1',
  },
  'client-2': {
    label: '💻 client-2',
    color: '#ba68c8',
    x: -555,
    y: 160,
    group: 'client',
    description: 'Frontend React Client Instance 2',
  },

  // ─── Server Cluster ───
  'nginx-server': {
    label: '🌐 nginx-server',
    color: '#42a5f5',
    x: -375,
    y: 100,
    group: 'server',
    description: 'Core API Server Load Balancer',
  },
  'server-1': {
    label: '⚙️ server-1',
    color: '#66bb6a',
    x: -200,
    y: 80,
    group: 'server',
    description: 'Express API Backend Instance 1',
  },
  'server-2': {
    label: '⚙️ server-2',
    color: '#66bb6a',
    x: -200,
    y: 180,
    group: 'server',
    description: 'Express API Backend Instance 2',
  },
  'redis-external': {
    label: '🗄️ redis-external',
    color: '#ef5350',
    x: -200,
    y: -45,
    group: 'server',
    description: 'Shared Redis Cache, Queues, & Session Store',
  },
  'bull-server': {
    label: '🐂 bull-server',
    color: '#ffd54f',
    x: -200,
    y: -160,
    group: 'server',
    description: 'BullMQ Worker Process for AI & Email Queues',
  },

  // ─── External Services (Top) ───
  'mongodb atlas': {
    label: '🍃 mongodb atlas',
    color: '#4caf50',
    x: -330,
    y: -365,
    group: 'external',
    description: 'Managed MongoDB Atlas Database Cluster',
  },
  'nodemailer': {
    label: '✉️ nodemailer',
    color: '#ff7043',
    x: -160,
    y: -365,
    group: 'external',
    description: 'SMTP Email Dispatch Service',
  },
  'gemini': {
    label: '🤖 gemini',
    color: '#ab47bc',
    x: 10,
    y: -365,
    group: 'external',
    description: 'Google Gemini / Groq AI Inference Engine',
  },

  // ─── Mock-Server / Worker Cluster ───
  'worker-logs': {
    label: '📋 worker-logs',
    color: '#ffd54f',
    x: 150,
    y: -165,
    group: 'worker',
    description: 'Container Log Collector & Streamer',
  },
  'worker-health': {
    label: '💚 worker-health',
    color: '#4dd0e1',
    x: 320,
    y: -165,
    group: 'worker',
    description: 'Container Health & Metric Monitor',
  },
  'internal redis': {
    label: '🗄️ internal redis',
    color: '#ef5350',
    x: 150,
    y: -45,
    group: 'worker',
    description: 'Mock Engine Internal Route & Spec Cache',
  },
  'worker-server': {
    label: '⚙️ worker-server\n[ 1 ]   [ 2 ]',
    color: '#42a5f5',
    x: 150,
    y: 70,
    group: 'worker',
    description: 'Dynamic Project Container Lifecycle Manager',
  },
  'openresty-nginx uses lua': {
    label: '🌐 openresty-nginx uses lua',
    color: '#26c6da',
    x: 280,
    y: 215,
    widthConstraint: { minimum: 280 },
    group: 'worker',
    description: 'High-Performance OpenResty Lua Mock Gateway',
  },
  'new project': {
    label: '📦 new project',
    color: '#81c784',
    x: 410,
    y: -80,
    group: 'worker',
    description: 'Dynamically Provisioned Mock Container',
  },
  'project1': {
    label: '📦 project1',
    color: '#81c784',
    x: 410,
    y: 25,
    group: 'worker',
    description: 'Active Mock Project Instance 1',
  },
  'project2': {
    label: '📦 project2',
    color: '#81c784',
    x: 410,
    y: 130,
    group: 'worker',
    description: 'Active Mock Project Instance 2',
  },

  // ─── Telemetry Service ───
  'client': {
    label: '📊 client',
    color: '#89b4fa',
    x: 640,
    y: 40,
    group: 'telemetry',
    description: 'Telemetry Dashboard Single Page Application',
  },
  'server': {
    label: '📡 server',
    color: '#89b4fa',
    x: 640,
    y: 160,
    group: 'telemetry',
    description: 'Telemetry Ingestion & WebSocket Broadcast Server',
  },
  'redis': {
    label: '🗄️ redis',
    color: '#ef5350',
    x: 810,
    y: 100,
    group: 'telemetry',
    description: 'Telemetry Session & Metric Store',
  },
};

export const FIXED_EDGES = [
  // ─── 1. External Domains -> Ingress Gateway ───
  { from: 'client.mockapi.info', to: 'Domain-service/CDN/Nginx', label: 'HTTP/S', color: '#ce93d8' },
  { from: 'server.mockapi.info', to: 'Domain-service/CDN/Nginx', label: 'HTTP/S', color: '#42a5f5' },
  { from: 'curl-api.mockapi.info', to: 'Domain-service/CDN/Nginx', label: 'cURL', color: '#ec407a' },
  { from: 'opentelemetry.client.mockapi.info', to: 'Domain-service/CDN/Nginx', label: 'HTTPS', color: '#89b4fa' },
  { from: 'opntelemtry.server.mockapi.info', to: 'Domain-service/CDN/Nginx', label: 'HTTPS', color: '#89b4fa' },

  // ─── 2. Ingress Gateway -> Subsystem Entrypoints ───
  { from: 'Domain-service/CDN/Nginx', to: 'nginx-client', label: 'route', color: '#ce93d8' },
  { from: 'Domain-service/CDN/Nginx', to: 'nginx-server', label: 'route', color: '#42a5f5' },
  { from: 'Domain-service/CDN/Nginx', to: 'openresty-nginx uses lua', label: 'mock req', color: '#26c6da' },
  { from: 'Domain-service/CDN/Nginx', to: 'client', label: 'ui traffic', color: '#89b4fa' },
  { from: 'Domain-service/CDN/Nginx', to: 'server', label: 'otlp ingest', color: '#89b4fa' },

  // ─── 3. Client Subsystem Internal & Egress ───
  { from: 'nginx-client', to: 'client-1', label: 'proxy', color: '#ce93d8' },
  { from: 'nginx-client', to: 'client-2', label: 'proxy', color: '#ce93d8' },
  { from: 'client-1', to: 'nginx-server', label: 'api req', color: '#ba68c8' },
  { from: 'client-2', to: 'nginx-server', label: 'api req', color: '#ba68c8' },

  // ─── 4. Server Subsystem Internal & External ───
  { from: 'nginx-server', to: 'server-1', label: 'balance', color: '#42a5f5' },
  { from: 'nginx-server', to: 'server-2', label: 'balance', color: '#42a5f5' },
  { from: 'server-1', to: 'redis-external', label: 'cache', color: '#ef5350', dashes: true },
  { from: 'server-2', to: 'redis-external', label: 'cache', color: '#ef5350', dashes: true },
  { from: 'server-1', to: 'bull-server', label: 'enqueue', color: '#ffd54f' },
  { from: 'server-2', to: 'bull-server', label: 'enqueue', color: '#ffd54f' },
  { from: 'server-1', to: 'mongodb atlas', label: 'data', color: '#4caf50' },
  { from: 'server-2', to: 'mongodb atlas', label: 'data', color: '#4caf50' },

  // ─── 5. Bull Server Queue Processing & External Calls ───
  { from: 'bull-server', to: 'redis-external', label: 'job queue', color: '#ef5350', dashes: true },
  { from: 'bull-server', to: 'nodemailer', label: 'send mail', color: '#ff7043' },
  { from: 'bull-server', to: 'gemini', label: 'inference', color: '#ab47bc' },

  // ─── 6. Server <-> Mock-Server Interconnect ───
  { from: 'redis-external', to: 'worker-server', label: 'event sync', color: '#ffd54f', dashes: true },

  // ─── 7. Mock-Server / Worker Cluster Routing & State ───
  { from: 'openresty-nginx uses lua', to: 'internal redis', label: 'spec cache', color: '#ef5350', dashes: true },
  { from: 'openresty-nginx uses lua', to: 'new project', label: 'proxy', color: '#26c6da' },
  { from: 'openresty-nginx uses lua', to: 'project1', label: 'proxy', color: '#26c6da' },
  { from: 'openresty-nginx uses lua', to: 'project2', label: 'proxy', color: '#26c6da' },

  { from: 'worker-server', to: 'internal redis', label: 'state', color: '#ef5350', dashes: true },
  { from: 'worker-server', to: 'new project', label: 'provision', color: '#42a5f5' },
  { from: 'worker-server', to: 'project1', label: 'provision', color: '#42a5f5' },
  { from: 'worker-server', to: 'project2', label: 'provision', color: '#42a5f5' },

  { from: 'worker-logs', to: 'internal redis', label: 'sync', color: '#ffd54f', dashes: true },
  { from: 'worker-logs', to: 'new project', label: 'tail logs', color: '#ffd54f' },
  { from: 'worker-logs', to: 'project1', label: 'tail logs', color: '#ffd54f' },
  { from: 'worker-logs', to: 'project2', label: 'tail logs', color: '#ffd54f' },

  { from: 'worker-health', to: 'internal redis', label: 'sync', color: '#4dd0e1', dashes: true },
  { from: 'worker-health', to: 'new project', label: 'probe', color: '#4dd0e1' },
  { from: 'worker-health', to: 'project1', label: 'probe', color: '#4dd0e1' },
  { from: 'worker-health', to: 'project2', label: 'probe', color: '#4dd0e1' },

  // ─── 8. Telemetry-Service Internal ───
  { from: 'client', to: 'server', label: 'ws stream', color: '#89b4fa' },
  { from: 'server', to: 'redis', label: 'session store', color: '#ef5350', dashes: true },
];